project:
  type: website
  resources:
    - "current-syllabus.pdf"

website:
  title: "Advanced Program and Policy Evaluation (HPOL8539)"
  margin-footer: |
    ![](vu-logo.png)
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Slides"
        contents:
          - slides/lec_introduction.qmd
      - text: "Blog"
        href: blog/index.qmd
      - section: "Useful Links"
        contents:
          - text: Current Syllabus
            href: https://github.com/graveja0/HPOL8539-F2022/raw/main/current-syllabus.pdf
          - text: Causal Inference - The Mixtape (Cunningham)
            href: https://mixtape.scunning.com/
          - text: The Effect (Huntington-Klein)
            href: https://theeffectbook.net/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
