project:
  type: website
  resources:
    - "current-syllabus.pdf"

website:
  title: "Advanced Program and Policy Evaluation (HPOL8539)"
  margin-footer: |
    ![](vu-logo.png)
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Slides"
        contents:
          - text: Course Introduction
            href: slides/lec_introduction.qmd
          - text: Peer Review Assignment
            href: slides/peer-review-assignment.qmd
          - text: Extending Difference-in-Differences
            href: slides/difference-in-differences.qmd
      - section: "Case Studies"
        contents:
          - text: 1. Simulation as a Guide for Study Design and Inference
            href: https://graves-vanderbilt.shinyapps.io/HPOL8539-Simulation/
          - text: 2. Panel Data Methods I - Fixed, Random and Correlated Random Effects
            href: https://graves-vanderbilt.shinyapps.io/HPOL8539-panel-data-1/
      - text: "Blog"
        href: blog/index.qmd
      - section: "Useful Links"
        contents:
          - text: Current Syllabus
            href: https://github.com/graveja0/HPOL8539-F2022/raw/main/current-syllabus.pdf
          - text: Causal Inference - The Mixtape (Cunningham)
            href: https://mixtape.scunning.com/
          - text: The Effect (Huntington-Klein)
            href: https://theeffectbook.net/
          - text: Comprehensive Discussion of Difference-in-Differences
            href: https://diff.healthpolicydatascience.org/
          - text: Difference-in-Differences Respository (code, packages, etc.)
            href: https://asjadnaqvi.github.io/DiD/
          - text: Resources on multiple nextGen DID estimators
            href: https://kylebutts.com/did2s/articles/event_study.html
          - text: Mixtape Sessions
            href: https://github.com/Mixtape-Sessions
          - text: Stata2R Translator
            href: https://stata2r.github.io/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
