project:
  type: website
  resources:
    - "*.xlsx"

website:
  title: "Advanced Program and Policy Evaluation (HPOL8539)"
  margin-footer: |
    ![](vu-logo.png)
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - index.qmd
      - text: "Workshop Blog"
        href: blog/index.qmd
      - section: "Tools and Applications"
        contents:
          - text: Decision Tree Drawing Tool
            href: https://dare.shinyapps.io/tree/
          - text: Probabilistic Sensitivity Analysis (PSA)
            href: https://vanderbilt-health-economic-modeling.shinyapps.io/probabilistic-sensitivity-analysis/
execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
