project:
  type: website
  resources:
    - "*.xlsx"

website:
  title: "Advanced Program and Policy Evaluation (HPOL8539)"
  margin-footer: |
    ![](vu-logo.png)
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - index.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Blog"
        href: blog/index.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
