---
title: "Advanced Program and Policy Evaluation"
listing:
  - id: schedu
    contents:
      - schedule.qmd
editor_options: 
  chunk_output_type: console
---

```{r, echo = FALSE}
#| fig-align: center
library(downloadthis)
## Link in Github repo
download_link(
  link = "https://github.com/graveja0/HPOL8539-F2022/raw/main/current-syllabus.pdf",
  button_label = "Current Syllabus",
  button_type = "primary",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```

<!-- https://github.com/rstudio-conf-2022/teach-ds -->

<!-- https://rstudio-conf-2022.github.io/teach-ds/ -->

<!-- https://github.com/rstudio-conf-2022/teach-ds-learnr -->

<!-- https://mine-cetinkaya-rundel.github.io/teach-r-online/ -->

<!-- https://github.com/rstudio-education/dsbox -->

<!-- https://github.com/sta210-s22/website -->

<!-- https://cran.r-project.org/web/packages/colorspace/vignettes/colorspace.html -->

```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
library(gt)
schedule <- list(
  day1 = list(
    "8:45 - 10:45" = "L] Course Introduction and Mechanics"
  ), 
  day2 = list(
    "8:45 - 10:45" = "CS] Simulation as a Guide for Study Design, Estimation, and Inference"
  ), 
  day3 = list(
    "8:45 - 10:45" = "CS] Panel Data Methods I: Fixed, Random, and Correlated Random Effects Estimation"
  ), 
  day4 = list(
    "8:45 - 10:45" = "CS] Panel Data II: Difference-in-Differences Revisited"
  ), 
  day5 = list(
     "8:45 - 10:45" = "CS] Next Generation Difference-in-Differences Estimators"
  ),
  day6 = list(
     "8:45 - 10:45" = "CS] Nonlinear Differences-in-Differences and Functional Form Considerations"
  ), 
  day7 = list(
     "8:45 - 10:45" = "CS] Interrupted Time Series vs. Differences-in-Differences (Guest Lecture by Dr. Carrie Fry)"
  ), 
  day8 = list(
     "8:45 - 10:45" = "NC] NO CLASS"
  ),   
  day9 = list(
     "8:45 - 8:45" = "CAP] Peer Review Writeup Due",
     "8:45 - 10:45" = "NC] NO CLASS"
  ), 
  day10 = list(
     "8:45 - 10:45" = "CS] Statistical Inference for Policy Evaluation"
  ),  
  day11 = list(
     "8:45 - 10:45" = "CS] Synthetic Control Methods"
  ),     
  day12 = list(
     "8:45 - 10:45" = "CS] Quantile Treatment Effects and Changes-in-Changes"
  ),   
  day13 = list(
      "8:45 - 8:45" = "CAP] Draft Methods Writeup Due to Peer Reviewer",
     "8:45 - 10:45" = "CS] Partial Identification Methods: Treatment Effect Bounds"
  ),   
  day14 = list(
     "8:45 - 8:45" = "CAP] Your Review of Your Peer's Methods Writeup is Due Back to Them",
     "8:45 - 10:45" = "CS] Research Project Organization, Execution and Workflows: Best Practices"
  ),    
  day15 = list(
     "8:45 - 8:45" = "CAP] Final Methods Writeup Due to John",
     "8:45 - 10:45" = "CS] Student Methods Presentations"
  )  ,
   day16 = list(
     "8:45 - 8:45" = "CAP] GEE"
  )
)
schedule %>% 
  map(~(
  .x %>% 
  bind_rows() %>% 
  t() %>% 
  data.frame() %>% 
  rownames_to_column(var = "time") %>% 
  separate(time,into =c("start","stop"),sep=" - ") %>% 
  set_names(c("start","stop","desc")))) %>% 
  bind_rows(.id = "day") %>% 
  separate(desc, into = c("type","desc"), sep = "] ") %>% 
  gt() %>% 
  tab_header(title = "Schedule") %>% 
  fmt_time(columns = c(start,stop),time_style = 4) %>% 
  cols_hide(columns = c(type,day)) %>% 
  cols_label(
    start = "",
    stop = "",
    desc = ""
  ) %>% 
      tab_row_group(label = "December 8, 2022",
                rows = day=="day15") %>% 
        tab_row_group(label = "December 1, 2022",
                rows = day=="day14") %>% 
        tab_row_group(label = "November 16, 2022",
                rows = day=="day13") %>% 
        tab_row_group(label = "November 9, 2022",
                rows = day=="day12") %>% 
        tab_row_group(label = "November 2, 2022",
                rows = day=="day11") %>% 
        tab_row_group(label = "October 26, 2022",
                rows = day=="day10") %>% 
        tab_row_group(label = "October 19, 2022",
                rows = day=="day9") %>% 
        tab_row_group(label = "October 12, 2022",
                rows = day=="day8") %>% 
        tab_row_group(label = "October 5, 2022",
                rows = day=="day7") %>% 
        tab_row_group(label = "September 28, 2022",
                rows = day=="day6") %>% 
      tab_row_group(label = "September 21, 2022",
                rows = day=="day5") %>% 
      tab_row_group(label = "September 14, 2022",
                rows = day=="day4") %>% 
      tab_row_group(label = "September 7, 2022",
                rows = day=="day3") %>% 
      tab_row_group(label = "August 31, 2022",
                rows = day=="day2") %>% 
      tab_row_group(label = "August 24, 2022",
                rows = day=="day1") %>% 
  tab_style(
    style = list(
      cell_fill(color = "#8ACEFA")
    ),
    locations = cells_body(
      columns = c(start,stop,desc),
      rows = type=="L"
    )
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#8FFA8A")
    ),
    locations = cells_body(
      columns = c(start,stop,desc),
      rows = type=="CS"
    )
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#DF8AFA")
    ),
    locations = cells_body(
      columns = c(start,stop,desc),
      rows = type=="CAP"
      
    )
  )
  
#install.packages(c("learnr", "gradethis", "sortable", "learnrhash"))
```
